import './globals.css'

export const metadata = {
<<<<<<< HEAD
  title: 'LitHumDaddy',
  description: 'Your companion for Columbia\'s Core Curriculum',
=======
  title: 'Next.js',
  description: 'Generated by Next.js',
>>>>>>> c187e5c (firstPush)
}

import './globals.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
